version: '3.10'


services:

  front:
    image: sermalenk/skypro-front:lesson-35:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    restart: always
    ports:
      - '80:80'
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./.env
    environment:
      POSTGRES_HOST: db
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    ports:
      - '8000:8000'


  migrations:
      build:
        context: .
      depends_on:
        db:
          condition: service_healthy
      env_file: .env
      environment:
          POSTGRES_HOST: db
      command: python3 manage.py migrate

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/pg_data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    ports:
    - "5432:5432"
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}' ]
      interval: 5s
      timeout: 5s
      retries: 15


volumes:
  postgres_data:


