version: '3.10'


services:

  front:
    image: sermalenk/skypro-front:lesson-35
    restart: always
    ports:
      - '80:80'
    depends_on:
      - api
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf/.d/default.conf
      - ./src/static:/opt/static

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./.env
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '8000:8000'
    volumes:
      - ./todolist:/app

  migrations:
      build:
        context: .
      depends_on:
        db:
          condition: service_healthy
      volumes:
        - ./.env:/app/.env
      command: python3 manage.py migrate

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/pg_data
    environment:
      POSTGRES_USER: todolist
      POSTGRES_PASSWORD: 123456qwerty
      POSTGRES_DB: todolist_db
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    restart: always
    ports:
    - "5432:5432"
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}']


volumes:
  postgres_data:


