version: '1.0'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: 123456qwerty
      POSTGRES_DB: todolist_db
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    restart: always
    ports:
    - "5432:5432"




volumes:
  postgres_data: